"""Meta tools for creating skills, agent profiles, and planning artifacts."""

import re
from pathlib import Path

from ..tool_events import emit_call, emit_return

_NAME_RE = re.compile(r"^[a-z0-9][a-z0-9\-]*$")


async def create_skill(name: str, description: str, instructions: str) -> str:
    """Persist a new skill to ~/.yaac/skills/ so it's available in all future sessions and auto-discovered locations.

    Args:
        name: Lowercase alphanumeric with hyphens (e.g. 'deploy-aws').
        description: One-line description shown in the catalog.
        instructions: Full instructions in Markdown format.

    Returns:
        Success or error message.
    """
    emit_call("create_skill", {"name": name})

    if not _NAME_RE.match(name):
        result = "Error: name must be lowercase alphanumeric with hyphens (e.g. 'deploy-aws')."
        emit_return("create_skill", result)
        return result

    skill_dir = Path.home() / ".yaac" / "skills" / name
    skill_file = skill_dir / "SKILL.md"

    try:
        skill_dir.mkdir(parents=True, exist_ok=True)
        content = f"---\nname: {name}\ndescription: {description}\n---\n\n{instructions}\n"
        skill_file.write_text(content, encoding="utf-8")

        # Reload the registry so the skill is immediately available
        from ..skills import init_skills
        init_skills()

        result = f"Skill '{name}' created at {skill_file} and loaded into the catalog."
    except Exception as e:
        result = f"Error creating skill: {e}"

    emit_return("create_skill", result)
    return result


async def create_agent_profile(name: str, description: str, system_prompt: str) -> str:
    """Persist a new agent profile to ~/.yaac/agents/ for use with spawn_subagent.

    Args:
        name: Lowercase alphanumeric with hyphens (e.g. 'test-writer').
        description: What this agent specializes in.
        system_prompt: System prompt extension for this agent.

    Returns:
        Success or error message.
    """
    emit_call("create_agent_profile", {"name": name})

    if not _NAME_RE.match(name):
        result = "Error: name must be lowercase alphanumeric with hyphens."
        emit_return("create_agent_profile", result)
        return result

    profile_dir = Path.home() / ".yaac" / "agents" / name
    profile_file = profile_dir / "AGENT.md"

    try:
        profile_dir.mkdir(parents=True, exist_ok=True)
        content = f"---\nname: {name}\ndescription: {description}\n---\n\n{system_prompt}\n"
        profile_file.write_text(content, encoding="utf-8")
        result = (
            f"Agent profile '{name}' created at {profile_file}. "
            f"Use spawn_subagent with profile='{name}' to invoke it."
        )
    except Exception as e:
        result = f"Error creating agent profile: {e}"

    emit_return("create_agent_profile", result)
    return result


async def plan_mode(task: str, steps: list[str], directory: str = ".") -> str:
    """Create or update a TODO.md execution plan for complex tasks.

    Args:
        task: Short description of the complex task being planned.
        steps: Ordered checklist of steps required to complete the task.
        directory: Directory where TODO.md should be written. Defaults to cwd.

    Returns:
        Success or error message.
    """
    emit_call("plan_mode", {"task": task, "steps": steps, "directory": directory})

    if not task.strip():
        result = "Error: task must not be empty."
        emit_return("plan_mode", result)
        return result

    normalized_steps = [step.strip() for step in steps if step.strip()]
    if not normalized_steps:
        result = "Error: steps must include at least one non-empty item."
        emit_return("plan_mode", result)
        return result

    todo_dir = Path(directory).expanduser().resolve()
    todo_file = todo_dir / "TODO.md"

    try:
        todo_dir.mkdir(parents=True, exist_ok=True)
        lines = [
            f"# TODO - {task.strip()}",
            "",
            "## Steps",
            *[f"- [ ] {step}" for step in normalized_steps],
            "",
            "## Notes",
            "- Generated by YAAC plan mode for a complex task.",
            "",
        ]
        todo_file.write_text("\n".join(lines), encoding="utf-8")
        result = f"Plan mode wrote {todo_file} with {len(normalized_steps)} steps."
    except Exception as e:
        result = f"Error creating TODO.md: {e}"

    emit_return("plan_mode", result)
    return result
